version: '2'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cookbook
    ports:
      - "5432:5432"
    volumes:
      - cookbook-db-data:/var/lib/postgresql/data

volumes:
  cookbook-db-data:
